const recipes = [
  {
    name: "Spaghetti Carbonara",
    chef: "Chef Mario",
    totalRatings: 500,
    avgRating: 4.8,
    uploadedOn: "2024-01-15",
    mealType: "Dinner",
    dishType: "Pasta",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A classic Italian pasta dish with a creamy egg-based sauce and crispy pancetta.",
    imgUrl: "https://i.pinimg.com/564x/a9/0e/e4/a90ee4bca901e935a7a406a7d90ca6c2.jpg",
  },
  {
    name: "Chicken Alfredo",
    chef: "Chef Luigi",
    totalRatings: 300,
    avgRating: 4.5,
    uploadedOn: "2024-02-10",
    mealType: "Dinner",
    dishType: "Pasta",
    testKitchenApproved: true,
    contestWinner: false,
    featured: true,
    description: "A rich and creamy pasta dish with tender chicken and a savory Alfredo sauce.",
    imgUrl: "https://bellyfull.net/wp-content/uploads/2021/02/Chicken-Alfredo-blog-4-768x1024.jpg",
  },
  {
    name: "Margherita Pizza",
    chef: "Chef Giovanni",
    totalRatings: 800,
    avgRating: 4.9,
    uploadedOn: "2024-03-05",
    mealType: "Dinner",
    dishType: "Pizza",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A classic Italian pizza with fresh tomatoes, mozzarella, and basil.",
    imgUrl: "https://cdn.loveandlemons.com/wp-content/uploads/2023/07/margherita-pizza-recipe.jpg",
  },
  {
    name: "Caesar Salad",
    chef: "Chef Antonio",
    totalRatings: 200,
    avgRating: 4.3,
    uploadedOn: "2024-04-20",
    mealType: "Lunch",
    dishType: "Salad",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A fresh and crisp salad with romaine lettuce, croutons, and Caesar dressing.",
    imgUrl: "https://cdn.loveandlemons.com/wp-content/uploads/2024/12/caesar-salad-recipe-1160x1567.jpg",
  },
  {
    name: "Tiramisu",
    chef: "Chef Maria",
    totalRatings: 600,
    avgRating: 4.7,
    uploadedOn: "2024-05-15",
    mealType: "Dessert",
    dishType: "Cake",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.",
    imgUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Tiramisu_-_Raffaele_Diomede.jpg/375px-Tiramisu_-_Raffaele_Diomede.jpg",
  },
  {
    name: "Beef Bourguignon",
    chef: "Chef Pierre",
    totalRatings: 450,
    avgRating: 4.6,
    uploadedOn: "2024-06-01",
    mealType: "Dinner",
    dishType: "Stew",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A hearty French stew made with beef braised in red wine, mushrooms, and onions.",
    imgUrl: "https://cafedelites.com/wp-content/uploads/2018/02/Beef-Bourgignon-IMAGE-RECIPE-17-768x1152.jpg",
  },
  {
    name: "Vegetable Stir Fry",
    chef: "Chef Mei",
    totalRatings: 350,
    avgRating: 4.4,
    uploadedOn: "2024-07-10",
    mealType: "Lunch",
    dishType: "Stir Fry",
    testKitchenApproved: true,
    contestWinner: false,
    featured: true,
    description: "A quick and healthy stir fry with a mix of fresh vegetables and a savory sauce.",
    imgUrl: "https://therecipecritic.com/wp-content/uploads/2019/08/vegetable_stir_fry.jpg",
  },
  {
    name: "Chocolate Lava Cake",
    chef: "Chef Sophie",
    totalRatings: 700,
    avgRating: 4.8,
    uploadedOn: "2024-08-05",
    mealType: "Dessert",
    dishType: "Cake",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A decadent chocolate cake with a gooey, molten center.",
    imgUrl: "https://www.allrecipes.com/thmb/3MHKBrVtQkX_KoPdaxPY_HgWyvk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/276304lava-cakeKim-e03d3bc55516400e8d05b8d84b524b73.jpg",
  },
  {
    name: "Shrimp Scampi",
    chef: "Chef Luca",
    totalRatings: 400,
    avgRating: 4.5,
    uploadedOn: "2024-09-12",
    mealType: "Dinner",
    dishType: "Seafood",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A flavorful dish of shrimp cooked in a garlic butter sauce with white wine and lemon.",
    imgUrl: "https://static01.nyt.com/images/2022/06/02/dining/ShrimpScampi_thumb/ShrimpScampi_thumb-master768-v2.jpg?quality=75&auto=webp",
  },
  {
    name: "Greek Salad",
    chef: "Chef Elena",
    totalRatings: 250,
    avgRating: 4.2,
    uploadedOn: "2024-10-18",
    mealType: "Lunch",
    dishType: "Salad",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A refreshing salad with tomatoes, cucumbers, olives, and feta cheese.",
    imgUrl: "https://cdn.loveandlemons.com/wp-content/uploads/2019/07/greek-salad-2-786x1024.jpg",
  },
  {
    name: "Beef Tacos",
    chef: "Chef Carlos",
    totalRatings: 550,
    avgRating: 4.7,
    uploadedOn: "2024-11-22",
    mealType: "Dinner",
    dishType: "Tacos",
    testKitchenApproved: true,
    contestWinner: false,
    featured: true,
    description: "Spicy beef tacos with fresh toppings and a zesty lime crema.",
    imgUrl: "https://feelgoodfoodie.net/wp-content/uploads/2017/04/Ground-Beef-Tacos-9.jpg",
  },
  {
    name: "Pancakes",
    chef: "Chef Emily",
    totalRatings: 900,
    avgRating: 4.9,
    uploadedOn: "2024-12-30",
    mealType: "Breakfast",
    dishType: "Pancakes",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Fluffy pancakes served with maple syrup and fresh berries.",
    imgUrl: "https://cdn.loveandlemons.com/wp-content/uploads/2025/01/pancakes-1160x1581.jpg",
  },
  {
    name: "Chicken Curry",
    chef: "Chef Raj",
    totalRatings: 500,
    avgRating: 4.6,
    uploadedOn: "2025-01-15",
    mealType: "Dinner",
    dishType: "Curry",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A spicy and aromatic chicken curry with a blend of Indian spices.",
    imgUrl: "https://www.allrecipes.com/thmb/4xmE8lu1TSg893xk93wk20AKJcs=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/46822-indian-chicken-curry-ii-DDMFS-4x3-39160aaa95674ee395b9d4609e3b0988.jpg",
  },
  {
    name: "Vegetable Lasagna",
    chef: "Chef Sofia",
    totalRatings: 300,
    avgRating: 4.4,
    uploadedOn: "2025-02-10",
    mealType: "Dinner",
    dishType: "Pasta",
    testKitchenApproved: true,
    contestWinner: false,
    featured: true,
    description: "A layered pasta dish with a mix of vegetables and creamy béchamel sauce.",
    imgUrl: "https://cookieandkate.com/images/2017/12/best-vegetable-lasagna-recipe-3-768x1151.jpg",
  },
  {
    name: "Sushi Rolls",
    chef: "Chef Hiroshi",
    totalRatings: 750,
    avgRating: 4.8,
    uploadedOn: "2025-03-05",
    mealType: "Lunch",
    dishType: "Sushi",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Fresh sushi rolls with a variety of fillings, served with soy sauce and wasabi.",
    imgUrl: "https://www.gimmesomeoven.com/wp-content/uploads/2020/05/How-To-Make-Sushi-Maki-Rolls-4-2-768x1120.jpg",
  },
  {
    name: "Chocolate Chip Cookies",
    chef: "Chef Olivia",
    totalRatings: 1000,
    avgRating: 4.9,
    uploadedOn: "2025-04-20",
    mealType: "Dessert",
    dishType: "Cookies",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Classic chocolate chip cookies with a soft and chewy texture.",
    imgUrl: "https://sallysbakingaddiction.com/wp-content/uploads/2013/05/classic-chocolate-chip-cookies-850x1276.jpg",
  },
  {
    name: "Beef Burger",
    chef: "Chef Jake",
    totalRatings: 600,
    avgRating: 4.7,
    uploadedOn: "2025-05-15",
    mealType: "Dinner",
    dishType: "Burger",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A juicy beef burger with all the classic toppings and a side of fries.",
    imgUrl: "https://simplehomeedit.com/wp-content/uploads/2024/03/Homemade-Beef-Burgers-4-768x1024.webp",
  },
  {
    name: "Vegetable Soup",
    chef: "Chef Lily",
    totalRatings: 200,
    avgRating: 4.3,
    uploadedOn: "2025-06-01",
    mealType: "Lunch",
    dishType: "Soup",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A comforting vegetable soup with a mix of seasonal vegetables.",
    imgUrl: "https://www.inspiredtaste.net/wp-content/uploads/2018/10/Homemade-Vegetable-Soup-Recipe-1-1200-768x1152.jpg",
  },
  {
    name: "Cheesecake",
    chef: "Chef Emma",
    totalRatings: 800,
    avgRating: 4.8,
    uploadedOn: "2025-07-10",
    mealType: "Dessert",
    dishType: "Cake",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A creamy cheesecake with a graham cracker crust and a topping of fresh berries.",
    imgUrl: "https://sallysbakingaddiction.com/wp-content/uploads/2018/05/perfect-cheesecake-recipe-850x1276.jpg",
  },
  {
    name: "Fish Tacos",
    chef: "Chef Diego",
    totalRatings: 400,
    avgRating: 4.5,
    uploadedOn: "2025-08-05",
    mealType: "Dinner",
    dishType: "Tacos",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "Crispy fish tacos with a tangy slaw and a drizzle of chipotle sauce.",
    imgUrl: "https://www.recipetineats.com/tachyon/2016/05/Fish-Tacos_4-1.jpg?resize=900%2C1260&zoom=0.725&quality=65",
  },
  {
    name: "Chicken Noodle Soup",
    chef: "Chef Noah",
    totalRatings: 300,
    avgRating: 4.4,
    uploadedOn: "2025-09-12",
    mealType: "Lunch",
    dishType: "Soup",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A comforting chicken noodle soup with tender chicken and hearty vegetables.",
    imgUrl: "https://sallysbakingaddiction.com/wp-content/uploads/2015/01/light-creamy-chicken-noodle-soup-1-850x1276.jpg",
  },
  {
    name: "Apple Pie",
    chef: "Chef Grace",
    totalRatings: 700,
    avgRating: 4.7,
    uploadedOn: "2025-10-18",
    mealType: "Dessert",
    dishType: "Pie",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A classic apple pie with a flaky crust and a sweet cinnamon-spiced filling.",
    imgUrl: "https://www.allrecipes.com/thmb/y4A1u56wlxTpMexUFWXQxNyZz8k=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Screen-Shot-2022-01-30-at-8.33.07-PM-9fbdb6fefa41482d8a1dc1f56266d8fb.png",
  },
  {
    name: "Chocolate Fondue",
    chef: "Chef Zoe",
    totalRatings: 300,
    avgRating: 4.4,
    uploadedOn: "2026-12-30",
    mealType: "Dessert",
    dishType: "Fondue",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A fun and interactive dessert with melted chocolate and a variety of dippable treats.",
    imgUrl: "https://www.simplyrecipes.com/thmb/9w3cVI7PIcD__0tXnpU8kWaqNi0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Chocolate-Fondue-Recipe-Lead-Shot-6a-SERP-48a91a6838b6456597b5de8e464f80b8.jpg",
  },
];

export default recipes;